const test=require('node:test'),assert=require('node:assert/strict');
const d=require('../.test-build/src/lib/domain.js');
const p={id:'00000000-0000-4000-8000-000000000001',title:'Tas',price:100000,image_url:'https://example.com/a.jpg',images:[],variants:[{name:'Hitam',image:'',stock:8}],stock:8,is_active:true};
test('same product and variant merge quantities',()=>{const a=d.addCartLine([],p,'Hitam');assert.equal(d.addCartLine(a,p,'Hitam')[0].quantity,2)});
test('different variants remain distinct',()=>{const b={...p,variants:[...p.variants,{name:'Putih',image:'',stock:2}]};assert.equal(d.addCartLine(d.addCartLine([],b,'Hitam'),b,'Putih').length,2)});
test('variant is mandatory when product has variants',()=>assert.throws(()=>d.addCartLine([],p,'')));
test('unknown variant cannot enter cart',()=>assert.throws(()=>d.addCartLine([],p,'fake')));
test('out of stock variant is rejected',()=>assert.throws(()=>d.addCartLine([],{...p,variants:[{name:'Hitam',image:'',stock:0}]},'Hitam')));
test('variant stock is tracked independently from other variants',()=>{const product={...p,variants:[{name:'Hitam',image:'',stock:1},{name:'Putih',image:'',stock:4}]};assert.throws(()=>d.addCartLine(d.addCartLine([],product,'Hitam'),product,'Hitam'));assert.equal(d.addCartLine([],product,'Putih').length,1);});
test('variant without initialized stock is unavailable',()=>assert.throws(()=>d.addCartLine([],{...p,variants:[{name:'Hitam',image:''}]},'Hitam')));
test('unlimited variant stock remains available',()=>{const product={...p,variants:[{name:'Hitam',image:'',stock:null}]};assert.equal(d.addCartLine([],product,'Hitam')[0].quantity,1);});
test('unlimited product stock remains available without variants',()=>{const product={...p,variants:[],stock:null};assert.equal(d.addCartLine([],product,'')[0].quantity,1);});
test('product-level stock still limits products without variants',()=>{const product={...p,variants:[],stock:1};assert.throws(()=>d.addCartLine(d.addCartLine([],product,''),product,''));});
test('inactive product is rejected',()=>assert.throws(()=>d.addCartLine([],{...p,is_active:false},'Hitam')));
test('quantities are integers only',()=>assert.throws(()=>d.setCartQuantity(d.addCartLine([],p,'Hitam'),p.id,'Hitam',1.5)));
test('empty cart is rejected',()=>assert.throws(()=>d.checkoutItems([])));
test('checkout serializes no price or customer-controlled totals',()=>{const v=d.checkoutItems(d.addCartLine([],p,'Hitam'));assert.deepEqual(Object.keys(v[0]).sort(),['product_id','quantity','variant']);});
test('display shipping threshold',()=>{assert.deepEqual(d.cartTotals(d.addCartLine([],p,'Hitam'),10000,100000),{subtotal:100000,shipping:0,total:100000});});
test('Indonesian phone normalization',()=>assert.equal(d.normalizePhone('0812-3456-7890'),'6281234567890'));
test('phone invalid input rejected',()=>assert.throws(()=>d.normalizePhone('abc')));
test('URL javascript not accepted',()=>assert.equal(d.safeImageUrl('javascript:alert(1)'),''));
test('data URLs not accepted',()=>assert.equal(d.safeImageUrl('data:image/svg+xml,anything'),''));
test('secure image URL preserved',()=>assert.equal(d.safeImageUrl('https://example.com/a.png'),'https://example.com/a.png'));
test('WA message encoded as a whole, including & and new lines',()=>{const url=d.whatsappUrl('6281234567890','A&B\n#order');assert.equal(new URL(url).searchParams.get('text'),'A&B\n#order')});
test('CSV formula injection is neutralized',()=>assert.equal(d.csvCell('=1+1'),'"\'=1+1"'));
test('corrupt stored cart is discarded',()=>assert.deepEqual(d.parseCart('bad'),[]));
test('stored cart survives roundtrip',()=>{const cart=d.addCartLine([],p,'Hitam');assert.deepEqual(d.parseCart(JSON.stringify(cart)),cart)});
test('hostile stored qty is discarded',()=>assert.deepEqual(d.parseCart(JSON.stringify([{...d.addCartLine([],p,'Hitam')[0],quantity:1e9}])),[]));
test('customer fields validated',()=>assert.throws(()=>d.validateCustomer({name:'',phone:'081234567890',address:'Jalan',note:''})));
test('order access backup restores only a valid versioned recovery key',()=>{const access={requestId:'00000000-0000-4000-8000-000000000001',receiptToken:'a'.repeat(64),signature:'b'.repeat(64)};assert.deepEqual(d.parseOrderAccessBackup(JSON.stringify({format:'zyha-order-access',version:1,orderNumber:'ZYHA-0123456789ABCDEF0123456789ABCDEF',...access})),access);});
test('order access backup rejects malformed or unsupported files',()=>{assert.throws(()=>d.parseOrderAccessBackup('not json'));assert.throws(()=>d.parseOrderAccessBackup(JSON.stringify({format:'zyha-order-access',version:2,orderNumber:'ZYHA-0123456789ABCDEF0123456789ABCDEF',requestId:'00000000-0000-4000-8000-000000000001',receiptToken:'a'.repeat(64),signature:'b'.repeat(64)})));});
test('order access backup contains no customer personal data',()=>{const json=d.serializeOrderAccessBackup({requestId:'00000000-0000-4000-8000-000000000001',receiptToken:'a'.repeat(64),signature:'b'.repeat(64)},'ZYHA-0123456789ABCDEF0123456789ABCDEF');assert.deepEqual(Object.keys(JSON.parse(json)).sort(),['format','orderNumber','receiptToken','requestId','signature','version'].sort());assert.doesNotMatch(json,/alamat|address|telepon|phone/i);});
test('article slugs normalize accents and reject empty identifiers',()=>{assert.equal(d.articleSlug('Cerita Tas Terbaru'),'cerita-tas-terbaru');assert.equal(d.articleSlug('Kualitas & Gaya'),'kualitas-gaya');assert.throws(()=>d.articleSlug('---'));});
test('footer links allow HTTPS and same-site paths only',()=>{assert.equal(d.safeFooterHref('https://example.com/info'),'https://example.com/info');assert.equal(d.safeFooterHref(' /kebijakan'),'/kebijakan');assert.throws(()=>d.safeFooterHref('//example.com'));assert.throws(()=>d.safeFooterHref('/\\example.com'));assert.throws(()=>d.safeFooterHref('javascript:alert(1)'));});
test('product CSV import parses quoted commas and escaped quotes',()=>{const rows=d.parseProductCsv('\uFEFFtitle,price,description,category,image_url,stock,weight_grams,is_active\r\n"Tas, besar",125000,"Ringan, ""kuat""",Tas,,5,650,true');assert.deepEqual(rows,[{title:'Tas, besar',price:125000,description:'Ringan, "kuat"',category:'Tas',image_url:'',stock:5,weight_grams:650,is_active:true}]);});
test('product CSV import accepts the minimum schema and rejects unsafe data',()=>{assert.deepEqual(d.parseProductCsv('title,price\r\nTas,12000'),[{title:'Tas',price:12000,description:'',category:'',image_url:'',stock:null,weight_grams:0,is_active:true}]);assert.throws(()=>d.parseProductCsv('title,price\r\nTas,abc'));assert.throws(()=>d.parseProductCsv('title,price,image_url\r\nTas,12000,javascript:alert(1)'));assert.throws(()=>d.parseProductCsv('title,title,price\r\nTas,Other,12000'));assert.throws(()=>d.parseProductCsv('title,price,weight_grams\r\nTas,12000,-1'));});
test('structured checkout address requires Indonesian postal code',()=>{const customer={name:'Pembeli',address:'Jalan Melati 12',district:'Coblong',city:'Bandung',province:'Jawa Barat',postal_code:'40132',phone:'081234567890',note:''};assert.equal(d.validateCustomer(customer).postal_code,'40132');assert.throws(()=>d.validateCustomer({...customer,postal_code:'123'}));});
