const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const read = p => fs.existsSync(p) ? fs.readFileSync(p,'utf8') : '';
test('admin route uses a real Auth gate',()=>assert.match(read('Admin.tsx'),/AdminGate/));
test('browser never writes paid directly',()=>assert.doesNotMatch(read('App.tsx'),/\.update\(\{\s*status:\s*['"]paid/));
test('Admin settings do not expose payment-provider credentials',()=>assert.doesNotMatch(read('src/admin/Settings.tsx'),/server_key|client_key|payment_provider/i));
test('no decorative icon dependency in UI',()=>assert.doesNotMatch(read('App.tsx')+read('Admin.tsx'),/lucide-react|icon="✨"/));
test('one shot SQL exists and uses authoritative pricing',()=>assert.match(read('supabase-setup.sql'),/zyha_place_order/));
test('setup does not seed fake products or orders',()=>assert.doesNotMatch(read('supabase-setup.sql'),/insert into public\.(products|orders)\s*\([^;]*?values\s*\(['"]/i));
test('normal build requires typecheck',()=>assert.match(JSON.parse(read('package.json')).scripts.build,/typecheck/));
test('all relative modules are packaged',()=>require('node:child_process').execFileSync(process.execPath,['scripts/check-files.cjs'],{stdio:'pipe'}));
test('orders have no browser INSERT/UPDATE grants',()=>assert.doesNotMatch(read('supabase-setup.sql'),/grant\s+(?:all|insert|update)[^;]*on public\.orders[^;]*to (?:anon|authenticated)/i));
test('guest SQL RPCs are revoked from browser roles',()=>assert.match(read('supabase-setup.sql'),/revoke all on function public\.zyha_rate_limit[^;]+from public,anon,authenticated/s));
test('admin authorization never reads editable metadata',()=>assert.doesNotMatch(read('supabase-setup.sql').replace(/--[^\n]*/g,''),/user_metadata/));
test('setup stops on unrelated existing schema',()=>assert.match(read('supabase-setup.sql'),/ZYHA_SETUP_REQUIRES_EMPTY_PROJECT/));
test('idempotent checkout is serialized before insert',()=>assert.match(read('supabase-setup.sql'),/pg_advisory_xact_lock\(hashtextextended\(p_request_id/));
test('stock locks follow deterministic ordering',()=>assert.match(read('supabase-setup.sql'),/order by id for update/));
test('receipt proof is hashed and not public table access',()=>assert.match(read('supabase-setup.sql'),/receipt_hash=encode\(extensions\.digest\(p_receipt_token,'sha256'\)/));
test('browser callback never asserts payment success',()=>assert.doesNotMatch(read('src/shop/payment.ts'),/status:\s*['"]paid|Pembayaran Berhasil/));
test('gallery file uploads validate byte signatures',()=>{const s=read('src/lib/api.ts');assert.match(s,/137,80,78,71,13,10,26,10/);assert.match(s,/file.size\s*>\s*5\s*\*\s*1024\s*\*\s*1024/);});
test('application does not use former Supabase endpoint',()=>assert.doesNotMatch(read('supabaseClient.ts'),/hkhajycblrfslxnapogx/));
test('tailwind is built locally, not CDN script',()=>assert.doesNotMatch(read('index.html'),/cdn.tailwindcss.com/));
test('order inputs on frontend never set payment status',()=>assert.doesNotMatch(read('src/lib/api.ts'),/\.from\(['"]orders['"]\)\.update/));
test('duplicate auth sign-in does not unmount an existing admin workspace',()=>assert.match(read('src/components/AdminGate.tsx'),/event\s*===\s*'SIGNED_IN'\s*&&\s*authUser.current\s*!==\s*nextSession\?\.user.id/));
test('server normalizes variant names without changing customer data',()=>assert.match(read('supabase-setup.sql'),/new.variants=coalesce\(\(select jsonb_agg\(jsonb_build_object\('name',btrim/));
test('bootstrap email does not collide with auth.users.email column',()=>{const s=read('supabase-setup.sql');assert.match(s,/lower\(auth\.users\.email\)=lower\(v_admin_email\)/);assert.doesNotMatch(s,/declare email text=/);});
test('catalog URL pagination is a nonnegative integer',()=>assert.match(read('App.tsx'),/Math\.floor\(Number\(params\.get\('page'\)\)/));
test('store growth migration isolates wishlist rows and publishes content safely',()=>{const s=read('supabase/migrations/20261010000000_store_growth.sql');assert.match(s,/user_id = \(select auth\.uid\(\)\)/);assert.match(s,/status = 'published'/);assert.match(s,/zyha_attach_customer_order/);assert.match(s,/alter publication supabase_realtime add table public\.wishlist_items/);});
test('customer order linking is atomic and refuses ownership changes',()=>{const s=read('supabase/migrations/20261010000000_store_growth.sql');assert.match(s,/customer_user_id is null or customer_user_id = p_user_id/);assert.match(read('supabase/functions/rapid-api/index.ts'),/zyha_attach_customer_order/);});
test('customer content API helpers are exported outside the generic action handler',()=>{const s=read('src/lib/api.ts');assert.match(s,/^export async function getPublishedArticles/m);assert.match(s,/^export async function getWishlist/m);assert.match(s,/^export async function getCustomerOrderHistory/m);});
test('coupon redemption is server-side and serialized by coupon row lock',()=>{const s=read('supabase/migrations/20261010000000_store_growth.sql');assert.match(s,/zyha_place_order_with_coupon/);assert.match(s,/for update/);assert.match(s,/max_uses_per_customer/);assert.match(read('supabase/functions/rapid-api/index.ts'),/p_customer_key:\s*customerKey/);assert.match(read('src/shop/Checkout.tsx'),/validateCoupon/);});
test('product CSV import validates full file before one database insert',()=>{assert.match(read('src/lib/domain.ts'),/export function parseProductCsv/);assert.match(read('src/admin/Products.tsx'),/parseProductCsv/);assert.match(read('src/lib/api.ts'),/from\('products'\)\.insert\(rows\)/);});
test('Edge Function CORS allows Supabase API version header and explains fetch failures',()=>{assert.match(read('supabase/functions/_shared/server.ts'),/Access-Control-Allow-Headers.*x-supabase-api-version/);assert.match(read('src/lib/api.ts'),/domain toko tercantum tepat di ALLOWED_ORIGINS/);});
